"""Added phone, city, state, and address fields to User model

Revision ID: 25681a8b77f3
Revises: 
Create Date: 2024-09-15 12:55:54.327423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25681a8b77f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=150), nullable=False))
        batch_op.drop_column('address')
        batch_op.drop_column('state')
        batch_op.drop_column('city')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
